### ISSUE TITLE
Intall using local libv8 gem dependency

### ISSUE THREAD

**Issue by raquelhortab** [rubyjs/therubyracer#463] opened 2021-12-09 15:18 UTC
Hi,
I am trying to install the gem on an arm64 device. I cross-compiled v8 (I have got an arm64.release folder resulting from the compilation) but do not know where to put it. I also managed to successfully install libv8 by downloading a .gem file of the version I need for arm from rubygems and installing it running gem install path_to_gem. Finally, I also added this to the gemfile:

`gem 'libv8', path: '~/.gem/ruby/1.9.1/gems/libv8-3.16.14.11'`

However, when I run bundle install and it tries to install therubyracer, I get errors because it tries to compile the dependency again, although it is already installed.

doing `gem install therubyracer -v '0.12.2' -- --with-system-v8` does not work either and it tries to compile v8 anyway.

Can anyone help me get this done? I've already spent so many hours I do not know what else to do. Thanks!

PS: where should I put the cross-compiled v8 so my system detects it? I am using a version of an arm64 ubuntu.

**Comment by lloeki** [comment] 2023-12-04 14:22
Sorry but this gem is [unmaintained](https://github.com/rubyjs/therubyracer#status-unmaintained), so I will close this issue.

We recommend going with mini_racer + libv8-node. If you feel the issue is still relevant to either of those, please open an issue over there!

**Closed by lloeki** 2023-12-04 14:22 UTC
